# Generated by Django 4.0.5 on 2022-06-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedtest',
            name='report',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedtest',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='store.order'),
        ),
    ]
