# Generated by Django 4.0.5 on 2022-06-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.test'),
            preserve_default=False,
        ),
    ]
