# Generated by Django 4.0.5 on 2022-06-17 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_speciality_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(default='name', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='store.order'),
        ),
    ]
