# Generated by Django 4.0.5 on 2022-06-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_qualification_name_alter_report_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
