# Generated by Django 4.0.5 on 2022-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_address_alter_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_store',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
